# Generated by Django 6.0.2 on 2026-02-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
